const TESTNET = 'testnet'
const MAINNET = 'mainnet'
const NETWORK = process.env.NETWORK

const WALLET_NAME = 'ord'
const TEMP_WALLET_NAME = process.env.TEMP_WALLET_NAME

const CMD_PREFIX = ''

const FRONT_SERVER = '*'

// APP setting
const MIN_CARDINAL = 10
const ADDRESS_COUNT = NETWORK === MAINNET ? 1 : MIN_CARDINAL
const AMOUNT_PER_ADDRESS = NETWORK === MAINNET ? 1 : 4000

const INSCRIPTION_PATH = 'inscription'

module.exports = {
  MAINNET,
  TESTNET,
  NETWORK,
  WALLET_NAME,
  TEMP_WALLET_NAME,
  CMD_PREFIX,
  FRONT_SERVER,
  INSCRIPTION_PATH,
  MIN_CARDINAL,
  ADDRESS_COUNT,
  AMOUNT_PER_ADDRESS,
}
