const ORDER_STATUS_ORDERED = 1
const ORDER_STATUS_TRANSACTION_CONFIRMED = 2
const ORDER_STATUS_ORDINAL_INSCRIBED = 3
const ORDER_STATUS_FAILED = 4
const ORDER_STATUS_CONFIRMED = 5

const ERROR_UNKNOWN = 'Unknown error'
const ERROR_INVALID_PARAMTER = 'Invalid parameter'
const ERROR_INVALID_TXID = 'Invalid txid'
const ERROR_DUPLICATED_TXID = 'Duplicated txid'

module.exports = {
  ORDER_STATUS_ORDERED,
  ORDER_STATUS_TRANSACTION_CONFIRMED,
  ORDER_STATUS_ORDINAL_INSCRIBED,
  ORDER_STATUS_FAILED,
  ORDER_STATUS_CONFIRMED,
  ERROR_UNKNOWN,
  ERROR_INVALID_PARAMTER,
  ERROR_INVALID_TXID,
  ERROR_DUPLICATED_TXID,
}